<a href="https://colab.research.google.com/github/harshaelon/Machine-learning/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Libraries

In [ ]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

%matplotlib inline

# creating a dataset

In [ ]:
from sklearn.datasets import make_classification

# using the above library fucntion we can define how many output classes we need
# and it will create the dataset in such a way that it's already standardized
# means we dont need to do any standardization here.

In [ ]:
X,y = make_classification(n_samples=1000 , n_features=10 , n_classes = 2 , random_state = 1)

In [ ]:
# so the above function returns two things one the dependent feature and othere independent.

In [ ]:
X

array([[-2.10118662, -0.24720775, -1.98933489, ...,  2.07052553,
         0.09152688, -2.37639956],
       [ 0.32370343, -0.12689445, -1.30952433, ...,  1.18481987,
        -0.186802  ,  1.96932634],
       [ 2.23203753,  0.33412256, -0.85270339, ..., -0.06644818,
        -0.31388129,  1.49917393],
       ...,
       [-1.16966316,  0.2306405 , -2.71039374, ...,  0.02149968,
        -1.06680089,  0.52886752],
       [-2.64618249, -0.11784427,  0.14937733, ...,  0.34047267,
        -0.27694042, -0.87101392],
       [-4.07569534, -0.33130612, -0.11181622, ..., -0.4164757 ,
         0.36444447, -0.534328  ]])

In [ ]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0   -2.101187 -0.247208 -1.989335 -1.484556  1.128668 -0.925564  1.210290   
1    0.323703 -0.126894 -1.309524 -0.022738 -0.398725  0.280419  0.034598   
2    2.232038  0.334123 -0.852703  3.289016  0.331944  0.044767 -2.233844   
3   -0.428456  1.627132  0.484649  0.938373  1.339947 -0.869036  0.943132   
4    0.386012  0.338141 -0.186530  2.369137  1.667284 -0.979107  0.951526   
..        ...       ...       ...       ...       ...       ...       ...   
995 -1.148812 -0.048464  0.555170 -2.167311 -0.595136  0.237045 -1.241394   
996  1.585814  1.269868  1.193456  2.321360  0.222056  0.040255  2.260748   
997 -1.169663  0.230641 -2.710394 -3.217224 -1.509607  0.795293 -0.854581   
998 -2.646182 -0.117844  0.149377 -0.377960  2.755272 -1.983281 -1.865016   
999 -4.075695 -0.331306 -0.111816 -2.867222  2.200368 -1.802118 -1.288487   

            7         8         9  
0    2.070526  0.091527 -2.376400  
1    1.184820 -0.186802  1.969326  
2   -0.066448 -0.313881  1.499174  
3    0.713558 -0.468041  0.075341  
4    0.398790  0.729005  0.372213  
..        ...       ...       ...  
995 -0.144619 -0.136638 -1.363868  
996 -0.182916 -0.959332  0.263967  
997  0.021500 -1.066801  0.528868  
998  0.340473 -0.276940 -0.871014  
999 -0.416476  0.364444 -0.534328  

[1000 rows x 10 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train , X_test , y_train, y_test = train_test_split(X,y,test_size=0.30,random_state=42)

#Model Training

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
logistic = LogisticRegression()

In [ ]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [ ]:
y_pred = logistic.predict(X_test)

print(y_pred)

[0 1 1 1 1 0 0 1 0 0 1 0 1 1 0 0 1 0 0 1 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 1 0
 0 1 1 0 1 1 0 1 0 0 1 0 1 1 0 0 0 0 0 1 1 1 1 0 1 1 0 0 0 0 1 0 0 1 1 0 1
 1 0 1 0 1 1 1 1 0 0 1 1 0 1 1 0 1 1 0 0 1 1 0 0 0 0 0 0 1 0 0 1 1 1 0 1 0
 0 0 1 1 1 0 1 1 0 0 1 0 0 1 0 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 1 1 0 0 1 0 1
 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 0 1 1 1 0 0 0 1 0 1 1 0 1 1 1 1 1 1 0 1 0 0
 0 0 1 1 0 1 0 1 1 0 0 0 1 1 1 1 1 0 1 0 0 1 1 1 0 0 0 1 0 0 1 1 1 0 1 0 1
 1 0 0 1 0 0 1 0 0 0 1 0 1 1 0 0 0 0 1 1 1 1 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1
 1 1 1 1 1 1 0 1 1 0 1 0 1 1 1 0 0 1 0 1 0 1 1 1 0 0 0 0 0 0 1 0 1 1 1 0 1
 1 0 1 1]


In [ ]:
logistic.predict_proba(X_test)

array([[7.56177215e-01, 2.43822785e-01],
       [4.84836102e-02, 9.51516390e-01],
       [3.87988137e-01, 6.12011863e-01],
       [1.85088537e-03, 9.98149115e-01],
       [1.60346334e-01, 8.39653666e-01],
       [9.22124222e-01, 7.78757782e-02],
       [5.62021061e-01, 4.37978939e-01],
       [1.62487057e-01, 8.37512943e-01],
       [9.48213617e-01, 5.17863827e-02],
       [9.85415590e-01, 1.45844096e-02],
       [1.47178474e-01, 8.52821526e-01],
       [9.56508699e-01, 4.34913009e-02],
       [7.62186489e-02, 9.23781351e-01],
       [1.56886063e-01, 8.43113937e-01],
       [9.22297988e-01, 7.77020124e-02],
       [9.14375219e-01, 8.56247808e-02],
       [1.80059445e-01, 8.19940555e-01],
       [9.84404794e-01, 1.55952063e-02],
       [9.29122904e-01, 7.08770962e-02],
       [8.24601622e-03, 9.91753984e-01],
       [2.04042504e-01, 7.95957496e-01],
       [1.09332039e-01, 8.90667961e-01],
       [7.57470321e-01, 2.42529679e-01],
       [2.99443315e-01, 7.00556685e-01],
       [9.665409

In [ ]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report

In [ ]:
score = accuracy_score(y_test,y_pred)

print(score)

confusion = confusion_matrix(y_test,y_pred)

print(confusion)


classi = classification_report(y_test,y_pred)

print(classi)


0.8633333333333333
[[126  24]
 [ 17 133]]
              precision    recall  f1-score   support

           0       0.88      0.84      0.86       150
           1       0.85      0.89      0.87       150

    accuracy                           0.86       300
   macro avg       0.86      0.86      0.86       300
weighted avg       0.86      0.86      0.86       300



# HyperParameter Tuning and Cross Validation

1. Grid Search CV
2. Random Search CV

In [ ]:
model = LogisticRegression()

# working with parameters
penalty = ['l1','l2','elasticnet']


c_value =  [100,10,1.0,0.1,0.01]

solver = ['newton-cg','lbfgs','liblinear','sag','saga']

max_iter = [100,150,200,250]


In [ ]:
dict(penalty = penalty , C = c_value , solver=solver)

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1.0, 0.1, 0.01],
 'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']}

In [ ]:
params = dict(penalty = penalty , C = c_value , solver=solver)

In [ ]:
type(params)

dict

#Grid Search CV

here our goal is to find out the best parameters for the model.

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold()
grid = GridSearchCV(estimator = model , param_grid = params, scoring = 'accuracy', cv =cv , n_jobs=-1)

In [ ]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [ ]:
grid.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1169, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [ ]:
grid.best_params_

{'C': 0.01, 'penalty': 'l1', 'solver': 'saga'}

In [ ]:
grid.best_score_

0.85

In [ ]:
y_pred = grid.predict(X_test)

In [ ]:
score = accuracy_score (y_pred,y_test)

print(score)

print(classification_report(y_pred,y_test))

print(confusion_matrix(y_pred,y_test))

0.8733333333333333
              precision    recall  f1-score   support

           0       0.84      0.90      0.87       140
           1       0.91      0.85      0.88       160

    accuracy                           0.87       300
   macro avg       0.87      0.88      0.87       300
weighted avg       0.88      0.87      0.87       300

[[126  14]
 [ 24 136]]


In [ ]:
# we can see that there is increase in the accuracy and other performance metrics using this particular technique.

# Randomized Search CV

In [ ]:
from sklearn.model_selection import RandomizedSearchCV


In [ ]:
randomcv = RandomizedSearchCV(estimator = model , param_distributions= params,cv = 5 , scoring = 'accuracy')

In [ ]:
randomcv.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: 
30 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1169, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/us

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [ ]:
randomcv.best_score_

0.8428571428571429

In [ ]:
randomcv.best_params_

{'solver': 'saga', 'penalty': 'l2', 'C': 100}

In [ ]:
y_pred = randomcv.predict(X_test)

In [ ]:
score = accuracy_score (y_pred,y_test)

print(score)

print(classification_report(y_pred,y_test))

print(confusion_matrix(y_pred,y_test))

0.8633333333333333
              precision    recall  f1-score   support

           0       0.84      0.88      0.86       143
           1       0.89      0.85      0.87       157

    accuracy                           0.86       300
   macro avg       0.86      0.86      0.86       300
weighted avg       0.86      0.86      0.86       300

[[126  17]
 [ 24 133]]


In [ ]:
# advantage of randomized search cv is that it takes less time than gridsearch cv in case of large datasets.